Сначала выполняется код внутри блока try{}. Если в нём нет ошибок, то блок catch(err) игнорируется: выполнение доходит до конца try и потом далее, полностью пропуская catch. сли же в нём возникает ошибка, то выполнение try прерывается, и поток управления переходит в начало catch(err). Finaly – выполнится в любом случае.